### ISSUE TITLE
Any code?

### ISSUE THREAD

**Issue by sevagh** [fgkouv/DynamicProcessor#1]
Hello @fgkouv - I'm very interested in seeing some C++ examples of a transient shaper in action. Do you have any intention of continuing the work on this?

If not, do you remember what type of transient shaping algorithm you intended to use? The 2-envelope system?

**Comment by fgkouv** [comment]
Hey @sevagh, thanks for your interest! Unfortunately, I have not had the time to properly work on this so I've set the whole project aside for quite some time now. I've been meaning to restart doing some stuff for it, but I doubt it will be any time soon.

> do you remember what type of transient shaping algorithm you intended to use? The 2-envelope system?

Yes the original prototype was based on the 2-envelope system. A great explanation can be found in the [SPL Transient Designer manual](https://spl.audio/wp-content/uploads/transient_designer_2_9946_manual.pdf), but the main idea is for each control (**_attack_** and **_sustain_**) to make use of a couple of envelopes and operate a VCA based on their difference. Hope this helps!

**Comment by sevagh** [comment]
Thanks for the link. I'll see what I can figure out on my own.
